### ISSUE TITLE
Root typecheck fails: apps/idp/test/flow.test.ts:74, Bun.serve().port is number | undefined

### ISSUE THREAD

**Issue by torresmateo** [arcadeai-labs/mastra-contextual-governance#46]
**[implementer]** Found while working #10 (PR #44), outside that slice, so filing rather than fixing.

`bun run typecheck` at the repo root fails:

```
idp typecheck: test/flow.test.ts(74,3): error TS2322: Type 'number | undefined' is not assignable to type 'number'.
idp typecheck:   Type 'undefined' is not assignable to type 'number'.
idp typecheck: Exited with code 2
```

The line is `freePort()`'s return in `apps/idp/test/flow.test.ts`:

```ts
function freePort(): number {
  const probe = Bun.serve({ port: 0, fetch: () => new Response(null, { status: 404 }) });
  const { port } = probe;   // typed number | undefined against apps/idp's bun-types
  probe.stop(true);
  return port;
}
```

`apps/idp` is not a workspace member and resolves its own `bun-types` (it needs zod 4, so it
carries its own lockfile), which is why the same pattern typechecks in
`tools/loan/tests/conftest.py`'s TypeScript counterparts elsewhere and not here.

**Pre-existing, and `main` is red on it.** Introduced in d2b46ff ("Orca worktree hooks: port
blocks, both installs, and free test ports"); the last green run on `main` is ed4b898. The CI
`Typecheck` step runs `bun run typecheck`, which sweeps `apps/idp` via `--filter '*'`, so
every branch inherits the failure — including PR #44, whose own `bun test` (463 pass) and
`packages/*` typechecks are clean.

`bun test` is unaffected: the suite runs fine, only `tsc` objects.

🤖 Generated with [Claude Code](https://claude.com/claude-code)

**Comment by torresmateo** [comment]
**[driver]** Merged as `6acbb1f` (PR #48, squash). Review round 1: approve, 5/5 verified, no findings. `main` CI should be green again from this commit.

**What landed.** One file, `apps/idp/test/flow.test.ts`: `freePort()` narrows `Bun.serve().port` and throws with the observed value if it is not a number, instead of casting. One new test asserts the probe returns a port the OS will re-bind.

**To test locally:**

```sh
git checkout main && git pull
bun install && bun install --cwd apps/idp
bun run typecheck
```
Expected: exits 0, every workspace including `idp typecheck` clean.

```sh
bun test --cwd apps/idp
```
Expected tail: `41 pass, 0 fail`.

Follow-ups the implementer found and filed rather than fixed: #49, `apps/loan-app` and `apps/hooks` tsconfigs include only `src`, so their tests are never typechecked, and `apps/loan-app` carries a byte-identical `freePort()` that would fail the same way if it were.
